export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED";

export const CART_ADD_ITEMS = "CART_ADD_ITEMS";
export const CART_REMOVE_ITEMS = "CART_REMOVE_ITEMS";
export const CART_SHIPPING_ADDRESS = "CART_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAILED = "USER_PROFILE_UPDATE_FAILED";

export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILED = "ORDER_PAY_FAILED";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

//Order list at user profile panel
export const ORDER_LIST_PROFILE_REQUEST = "ORDER_LIST_PROFILE_REQUEST";
export const ORDER_LIST_PROFILE_SUCCESS = "ORDER_LIST_PROFILE_SUCCESS";
export const ORDER_LIST_PROFILE_FAILED = "ORDER_LIST_PROFILE_FAILED";
export const ORDER_LIST_PROFILE_RESET = "ORDER_LIST_PROFILE_RESET";

//Profile list at Admin panel
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILED = "USER_LIST_FAILED";
export const USER_LIST_RESET = "USER_LIST_RESET";

//Delete a user as Admin
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";

//User details at Admin panel
export const USER_PROFILE_DETAILS_REQUEST = "USER_PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAILED = "USER_PROFILE_DETAILS_FAILED";
export const USER_PROFILE_DETAILS_RESET = "USER_PROFILE_DETAILS_RESET";

//User details edit update at Admin panel
export const USER_EDIT_UPDATE_REQUEST = "USER_EDIT_UPDATE_REQUEST";
export const USER_EDIT_UPDATE_SUCCESS = "USER_EDIT_UPDATE_SUCCESS";
export const USER_EDIT_UPDATE_FAILED = "USER_EDIT_UPDATE_FAILED";
export const USER_EDIT_UPDATE_RESET = "USER_EDIT_UPDATE_RESET";

//Product delete as Admin
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED";

//Create Product as Admin
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAILED = "PRODUCT_CREATE_FAILED";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

//Product update edit as Admin
export const PRODUCT_UPDATE_EDIT_REQUEST = "PRODUCT_UPDATE_EDIT_REQUEST";
export const PRODUCT_UPDATE_EDIT_SUCCESS = "PRODUCT_UPDATE_EDIT_SUCCESS";
export const PRODUCT_UPDATE_EDIT_FAILED = "PRODUCT_UPDATE_EDIT_FAILED";
export const PRODUCT_UPDATE_EDIT_RESET = "PRODUCT_UPDATE_EDIT_RESET";

//Order list as Admin
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILED = "ORDER_LIST_FAILED";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

//Order set is Delivered
export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAILED = "ORDER_DELIVER_FAILED";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

//Product add review
export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAILED = "PRODUCT_CREATE_REVIEW_FAILED";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

//Top rated products
export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAILED = "PRODUCT_TOP_FAILED";
